language: java
branches:
  only:
    - master
install: echo 'Skipping mvn install' 
script: mvn clean test -U
notifications:
    on_success: never
    on_failure: always

cache:
  directories:
  - $HOME/.m2
