/* Generated by dbus-binding-tool; do not edit! */

#include <glib/gtypes.h>
#include <glib/gerror.h>
#include <dbus/dbus-glib.h>

G_BEGIN_DECLS

#ifndef DBUS_GLIB_CLIENT_WRAPPERS_org_jscsi_sg_SGTransport
#define DBUS_GLIB_CLIENT_WRAPPERS_org_jscsi_sg_SGTransport

static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
org_jscsi_sg_SGTransport_service_indication (DBusGProxy *proxy, const char * IN_initiatorPort, const char * IN_targetPort, const gint64 IN_lun, const GArray* IN_cdb, const gint64 IN_cmdRef, GError **error)

{
  return dbus_g_proxy_call (proxy, "serviceIndication", error, G_TYPE_STRING, IN_initiatorPort, G_TYPE_STRING, IN_targetPort, G_TYPE_INT64, IN_lun, dbus_g_type_get_collection ("GArray", G_TYPE_UCHAR), IN_cdb, G_TYPE_INT64, IN_cmdRef, G_TYPE_INVALID, G_TYPE_INVALID);
}

typedef void (*org_jscsi_sg_SGTransport_service_indication_reply) (DBusGProxy *proxy, GError *error, gpointer userdata);

static void
org_jscsi_sg_SGTransport_service_indication_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_INVALID);
  (*(org_jscsi_sg_SGTransport_service_indication_reply)data->cb) (proxy, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
org_jscsi_sg_SGTransport_service_indication_async (DBusGProxy *proxy, const char * IN_initiatorPort, const char * IN_targetPort, const gint64 IN_lun, const GArray* IN_cdb, const gint64 IN_cmdRef, org_jscsi_sg_SGTransport_service_indication_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_new (DBusGAsyncData, 1);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "serviceIndication", org_jscsi_sg_SGTransport_service_indication_async_callback, stuff, g_free, G_TYPE_STRING, IN_initiatorPort, G_TYPE_STRING, IN_targetPort, G_TYPE_INT64, IN_lun, dbus_g_type_get_collection ("GArray", G_TYPE_UCHAR), IN_cdb, G_TYPE_INT64, IN_cmdRef, G_TYPE_INVALID);
}
#endif /* defined DBUS_GLIB_CLIENT_WRAPPERS_org_jscsi_sg_SGTransport */

G_END_DECLS
